
DROP TABLE IF EXISTS polls;
CREATE TABLE IF NOT EXISTS polls (
  id INT(10) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  title VARCHAR (90) NOT NULL,
  --content text NOT NULL,
  hash VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  closed tinyint(3) unsigned DEFAULT '0');

DROP TABLE IF EXISTS `contents`;
CREATE TABLE IF NOT EXISTS contents (
  id INT(10) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  poll_id INT (10) NOT NULL,
  question VARCHAR (90) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(poll_id) REFERENCES polls(id) ON DELETE CASCADE ON UPDATE CASCADE);


DROP TABLE IF EXISTS `options`;
CREATE TABLE IF NOT EXISTS options (
  id INT(10) unsigned PRIMARY KEY AUTO_INCREMENT NOT NULL ,
  poll_id INT(10),
  content_id INT(10),
  value VARCHAR(90) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY (poll_id) REFERENCES polls(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (content_id) REFERENCES contents(id) ON DELETE CASCADE ON UPDATE CASCADE);

DROP TABLE IF EXISTS `votes`;
CREATE TABLE IF NOT EXISTS votes (
  id INT(10) unsigned PRIMARY KEY AUTO_INCREMENT NOT NULL,
  option_id INT (10) unsigned NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(option_id) REFERENCES options(id) ON DELETE CASCADE ON UPDATE CASCADE);

